### PR TITLE
Added "@vue-event" tag for "$emit" events

### PR DESCRIPTION
**Pull request by Kokosso**

### CODE REVIEW

**Comment by Kokosso** [comment]
Hello. How can I fix appveyor-error? I think that's an internal error and I cannot fix that.

**Comment by Kokosso** [comment]
It's problem with CI-process perhaps

**Comment by Kocal** [comment]
Hi, thanks for the contribution. I will try to get some time this week-end to review it.

For AppVeyor CI, I restared the build to see if the error is still here.

**Comment by Kocal** [comment]
Well this is nice, I've reviewed what you've done and it's great. :+1: 

I had to do some minors modification but I wasn't able to push them on this branch, so I've opened #174 and I will close this one.

**Pull request closed without merging**
